//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemExAutoservis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class name_databaseEntities : DbContext
    {
        public name_databaseEntities()
            : base("name=name_databaseEntities")
        {
        }
        private static name_databaseEntities _context;
        public static name_databaseEntities GetContext()
        {
            if (_context == null)
                _context = new name_databaseEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<orderuserlist> orderuserlist { get; set; }
        public virtual DbSet<shift> shift { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userlist> userlist { get; set; }
        public virtual DbSet<userrole> userrole { get; set; }
    }
}
